export const START_FETCHING_LISTS_JABATANS =
  "redux/lists/START_FETCHING_LISTS_JABATANS";
export const SUCCESS_FETCHING_LISTS_JABATANS =
  "redux/lists/SUCCESS_FETCHING_LISTS_JABATANS";
export const ERROR_FETCHING_LISTS_JABATANS =
  "redux/lists/ERROR_FETCHING_LISTS_JABATANS";

export const START_FETCHING_LISTS_SHIFTS =
  "redux/lists/START_FETCHING_LISTS_SHIFTS";
export const SUCCESS_FETCHING_LISTS_SHIFTS =
  "redux/lists/SUCCESS_FETCHING_LISTS_SHIFTS";
export const ERROR_FETCHING_LISTS_SHIFTS =
  "redux/lists/ERROR_FETCHING_LISTS_SHIFTS";

export const START_FETCHING_LISTS_KARYAWANS =
  "redux/lists/START_FETCHING_LISTS_KARYAWANS";
export const SUCCESS_FETCHING_LISTS_KARYAWANS =
  "redux/lists/SUCCESS_FETCHING_LISTS_KARYAWANS";
export const ERROR_FETCHING_LISTS_KARYAWANS =
  "redux/lists/ERROR_FETCHING_LISTS_KARYAWANS";
